# This workflow builds and pushes the backend Docker image to the GitHub Container Registry (GHCR)

name: Docker Build and Push to GHCR

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job builds and pushes the backend image
  build-and-push-backend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Grant the GITHUB_TOKEN permissions to write packages
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to the GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Extract metadata (tags and labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/eodt-backend

      # 4. Build and push the Docker image for the backend
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./src/backend  # The build context is your backend directory
          file: ./src/backend/Dockerfile # Specifies the path to the Dockerfile
          push: true # Actually push the image to the registry
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

